server {
    listen 8089;
    server_name _;
    error_log /dev/stderr warn;

    root /var/www/localhost/htdocs;
    index index.html;

    # Important: Home Assistant Ingress sends requests to a dynamic subpath (ex. /api/hassio_ingress/token/)
    # This location-block ensures that all requests are routed to the index.html, allowing the frontend to handle routing correctly.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Prevent caching so that changes in the redirect URL are reflected immediately
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location = /config-status.json {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
